name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build Unsigned iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Create GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Disable iOS Code Signing
        run: |
          cd ios

          sed -i '' 's/DevelopmentTeam = .*;/DevelopmentTeam = "";/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = "";/g' Runner.xcodeproj/project.pbxproj

          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' Runner.xcodeproj/project.pbxproj

          sed -i '' 's/CODE_SIGNING_ALLOWED = YES;/CODE_SIGNING_ALLOWED = NO;/g' Runner.xcodeproj/project.pbxproj

          sed -i '' 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' Runner.xcodeproj/project.pbxproj

          sed -i '' 's/CODE_SIGN_IDENTITY = ".*"/CODE_SIGN_IDENTITY = ""/g' Runner.xcodeproj/project.pbxproj

          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = .*/PROVISIONING_PROFILE_SPECIFIER = "";/g' Runner.xcodeproj/project.pbxproj

      - name: Build Unsigned iOS App
        run: |
          flutter build ios --release --no-codesign \
            --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}

      - name: Create Payload Folder
        run: mkdir -p Payload
        working-directory: build/ios/iphoneos

      - name: Copy Runner.app
        run: cp -R Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Create IPA File
        run: zip -r app.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ios-ipa
          path: build/ios/iphoneos/app.ipa
